# For more details, see https://docs.pi-hole.net/docker/

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      TZ: ${TZ}
      FTLCONF_webserver_api_password: ${ADMIN_PASSWORD}
      FTLCONF_dns_listeningMode: 'LOCAL'
      FTLCONF_dns_upstreams: '1.1.1.1;1.0.0.1'
      FTLCONF_database_maxDBdays: '90'
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./resolv.conf:/etc/resolv.conf:ro
    user: "0:0"
    restart: unless-stopped
